### ISSUE TITLE
What happens if new files are added during a scan?

### ISSUE THREAD

**Issue by ochompsky** [dennisrazumovsky/precizer#2]
In the output when first running precizer, I noticed it has a file count.  

What happens if the process is interrupted before the first run is complete?  Does it pick up the new files or run the same set?

**Comment by dennisrazumovsky** [comment]
> What happens if new files are added during a scan

It varies depending on whether the binary tree traversal of the file system has already visited the directory where the new file has been added. If the traversal process has already passed through that directory, the program will detect the new file during the next run. However, if the file appears in a directory that hasn't been traversed yet, information about it will be added to the database during the current execution of the program.

**Comment by dennisrazumovsky** [comment]
> What happens if the process is interrupted before the first run is complete?

Nothing critical will happen. The application is designed to be highly resilient to failures. All files that were traversed at the time of the failure will be saved in the database and the integrity of this database will NOT be compromised. Several seconds of program operation may be lost (this is the data that was in the cache and did not have time to be written to the database on disk)

> Does it pick up the new files or run the same set?

When the program will restart, it will begin traversing directories from the very beginning in search of changes (new files, changed files or deleted) and will compare with what is already in the database. If the file metadata has already been saved against the database, then the checksums for this file will not be recalculated and the program will proceed to examine the next file.
